server:
  port: ${PORT:8000}
  forward-headers-strategy: framework

spring:
  data:
    mongodb:
      uri: mongodb://172.31.26.116:27017/clexis-db
      database: clexis-db

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:loukdomvansorel@gmail.com}
    password: ${MAIL_PASSWORD:xxxxxxxxxxx}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
